### ISSUE TITLE
Support for async method

### ISSUE THREAD

**Issue by AlexPalma72** [csnemes/tracer#43]
Hi @csnemes, any plans for tracer to support async methods?

**Comment by csnemes** [comment]
The thought occured, but the generated IAsyncStateMachine complicates things a bit. Also I'm not 100% sure what the right behaviour should be? Because technically speaking it exits the async method right before the first await, yet if we look from common sense's perspective one would expect that the trace return entry gets to the end with the real return values. Anyway I'll plan to spend some time on this as one of my new projects also facing the same issue.

**Comment by csnemes** [comment]
Hi, I've maneged to figure out how to do it, so I epxect to finish and release the async support in the forthcoming weeks.

**Comment by csnemes** [comment]
Hi, the new 1.5.0 version of Tracer.Fody now properly rewrites async methods. Please give it a try.

**Comment by AlexPalma72** [comment]
Hi @csnemes,
Sorry to only reply back now but a lot of things going on.
I just verified with latest and all is working great now.

Thanks for the hard work.
