### ISSUE TITLE
Add ability to define a Call id that will be added as a log property

### ISSUE THREAD

**Issue by AlexPalma72** [csnemes/tracer#55]
Hi @csnemes , once again thanks for the great work.
So I need to add as a  log property a call id that would be defined on the TraceEnter and used again on the TraceLeave, this way would be easy to tied both calls together,, since when doing multi threaded  developments  the trance enter and leave calls get all mixed up and is difficult to follow them even when adding it to the database.
so not sure if this is already possible or would imply a change to the Tracer.
if a change was needed maybe the easiest way would be to define an interface that could then be implemented by the class something like IHasTracerCallId {string CallId {get;}} when implemented by a type then it would be call and passed as a parameter to both the TraceEnter and TraceLeave methods, if the class didn't implement that interface then null would be passed.

Thoughts?

**Comment by csnemes** [comment]
Hi, Thanks. 
First of all if you use multithreading in a synchronous way the thread Id would be a good candidate to correlate the entries and exits. If you use async it won't work as the exit might run on a different thread than the enter. For this scenario the easiest and the less intrusive way from Tracer's perspective would be to create a new Adapter (based on an existing one) and extend the TraceEnter and TraceLeave methods. There in the Enter you can create a unique id put it on a AsyncLocal (or on CallContext pre 4.6) so that Leave can get it from there. Of course it is possible to extend the rewriter to generate a unique id for each methodcall and pass it to enters and leaves. This would imply that every adapter should be updated to support the two new parameters. I've been thinking of extending the rewriter to add some kind of extensibility in terms of data logged/passed to the adapter, but I'm really at the starting point on this one.

**Comment by AlexPalma72** [comment]
Thanks , so I did what you suggested created a method called NewCallId on the static log and then added the implementation on the TracerAdapter, Using a AsyncLocal field and on the LogImp method of the tracer just added the Value to an event property called callId it works like a  champ and cause I have the NewCallId method I can determine where I want  to start a New Call Id it works very nice.

Once again thanks for the direction.
