### ISSUE TITLE
System.NotImplementedException for IEnumerator.Reset()

### ISSUE THREAD

**Issue by Janek91** [csnemes/tracer#58]
Calling https://github.com/csnemes/tracer/blob/8678931a8a3434b1ea3de406622c292e57da1ecc/Tracer.Log4net/Adapters/LoggerAdapter.cs#L481 from TraceLeave->GetRenderedFormat method causes NotImplementedException if Reset method was not implemented in particular IEnumerator passed as message parameter.
I encountered this i.e. when running this code:

`private static IEnumerable<Type> GetAllNotSealedClasses() => AllClasses.FromAssemblies(AppDomain.CurrentDomain.GetAssemblies()).Where(type => type.IsClass && !type.IsSealed);`

**Comment by csnemes** [comment]
The Reset needs to be there as the rendering gets to the end of the enumerable so you need to put the position back to the start. Otherwise the real code would receive an empty enumerator. Also I think that Reset is part of the IEnumerator contract so if you implement IEnumerator you shouldn't leave it as NotImplemented. I understand that this enumerator is within Unity so you don't have control over it. What you can do is either create a working enumerable by using ToList() at the end of the LINQ chain or put `LogUseSafeParameterRendering` into your app config with a `true` value. This setting will use a different parameter renderer which doesn't try to log enumerable values.
