### ISSUE TITLE
Log static doesn't work before logger is configured.

### ISSUE THREAD

**Issue by DewJunkie** [csnemes/tracer#61]
I just wanted to find out if there was a better solution or this had already been solved.
Here is what I want to solve.
- Tracer.Serilog.Log does not work in any class that does any logging prior to the logging being configured.  It gets a reference to the unconfigured Serilog.Log.Logger when the LoggerAdapter is constructed.

This isn't too much of an issue most of the time, but I have an Xamarin Android application which has multiple entry Activities.

In projects where this has been an issue, I've been cloning the Tracer.Serilog.Fody project and implementing the logger configuration in a static constructor like this.
https://gist.github.com/DewJunkie/30a720e4dcb8c7daa2d0ef19d0401ed9

I'm new to Fody.  Is it possible to have the LogManagerAdapter be in the Assembly that is being Weaved?  That would make things the easiest.  If not, then Tracer.Serilog.Fody could be split into 2
- Tracer.Serilog.Fody- provide default implementations pretty much as they are now.
- Tracer.Serilog.Fody.AppName - user created project that would provide a LogManagerAdapter which configures the Logger as in the above snippet.
- FodyWeavers.xml would need to allow for 2 assemblies in the event that the first options doesn't work.

Hopefully, this is reasonably clear.

**Comment by csnemes** [comment]
Thanks for the detailed description, I think I understood your problem clearly. I'll try to figure out some clever way to initialize the logger on demand (like injecting the static initalization somewhere).

**Comment by DewJunkie** [comment]
This maybe a little niche to spend too much time one.  Maybe in the weavers.cfg you could set a name of the type, which implements ILoggerConfiguration, that would be called from the static constructor of LogManagerAdapter.  Or I guess we wouldn't even need the interface.  Just that it implements the correct function signature.

**Comment by csnemes** [comment]
Unfortunately it is not really feasible to rewrite the adapter itself as the whole fody machinery works on the actual projects and not on the assemblies referenced by these projects. However with a trick you can delegate the initialization configuration to the weaver. If instead of GetLogger(Type) one would use GetLogger(Type initClassType, Type loggerType) he can inject the init class into the weaved assemblies, which will pass this information to the adapter where the adapter can create and instance of the initClassType and call a method by convention. I went down this path and had an almost :-) working solution, but the result was ugly. So cloning the adapter seems to be a more clean way of doing the init.
